// Generate SHA-256 integrity hashes for the flow SVG assets and write them into
// the GENERATED block of flow.config.ts. SvgInlineDirective verifies a fetched
// asset against its hash and refuses to inline a mismatch, so an SVG tampered
// after the build (bucket/CDN/deploy) fails closed. The hashes ship inside the
// JS bundle, which is itself integrity-protected via --subresource-integrity.
//
// Runs at the end of `pnpm svgo:flow`, which is what finalizes the asset bytes.

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { FLOW_OVERVIEWS, FLOW_SUBSYSTEMS } from '../src/app/help/flow/flow.config';

const here = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = resolve(here, '../src');
const CONFIG = resolve(here, '../src/app/help/flow/flow.config.ts');
const BEGIN = '// === GENERATED by `pnpm svgo:flow` — do not edit by hand ===';
const END = '// === END GENERATED ===';

const urls = [
   ...new Set(
      [...Object.values(FLOW_OVERVIEWS), ...Object.values(FLOW_SUBSYSTEMS)].map(item => item.svg),
   ),
];

const lines = urls.map(url => {
   const file = resolve(SRC_DIR, url.replace(/^\//, ''));
   const hash = createHash('sha256').update(readFileSync(file)).digest('base64url');
   return `   '${url}': 'sha256-${hash}',`;
});

const block = [
   BEGIN,
   '// SHA-256 (base64url) of each flow SVG asset. SvgInlineDirective rejects any',
   '// fetched asset whose bytes do not match',
   'export const FLOW_SVG_HASHES: Record<string, string> = {',
   ...lines,
   '};',
   END,
].join('\n');

const escape = (str: string) => str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const region = new RegExp(`${escape(BEGIN)}[\\s\\S]*?${escape(END)}`);

let source = readFileSync(CONFIG, 'utf8');
if (!region.test(source)) {
   throw new Error(`hash_flow_svgs: GENERATED markers not found in ${CONFIG}`);
}
source = source.replace(region, block);
writeFileSync(CONFIG, source);
console.log(`wrote ${urls.length} flow SVG hashes to flow.config.ts`);
