/* MIT License

Copyright (c) 2025-2026 Brad Schick

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE. */
export const FLOW_ANIM_MS = 420;

// Max path depth below top-level (limited because loops exists)
export const FLOW_MAX_DEPTH = 14;

export interface FlowItem {
   label: string;
   svg: string;
}

// Top-level entry points shown in the initial grid view and as path[0] of the
// route query string. Keys are the route segment values.
export const FLOW_OVERVIEWS: Record<string, FlowItem> = {
   'encryption': { label: 'Encryption', svg: '/assets/flow/v7/encryption.svg' },
   'decryption': { label: 'Decryption', svg: '/assets/flow/v7/decryption.svg' },
};

// Subprocesses keyed by the 2-character lowercase hex value of the blue byte
// of Lucidchart placeholder fill #f4d9NN. The same key is also the SVG
// data-target attribute value and the URL path segment. 'ff' is reserved
export const FLOW_SUBSYSTEMS: Record<string, FlowItem> = {
   '01': { label: 'Sign Block 0',         svg: '/assets/flow/v7/sign_cd0.svg' },
   '02': { label: 'Sign Block N',         svg: '/assets/flow/v7/sign_cdN.svg' },
   '03': { label: 'Encrypt Block 0',      svg: '/assets/flow/v7/encrypt_m0.svg' },
   '04': { label: 'Pack Block 0 AD',      svg: '/assets/flow/v7/pack_ad0.svg' },
   '05': { label: 'Derive Signing Key',   svg: '/assets/flow/v7/derive_enc_kS.svg' },
   '06': { label: 'Obtain Input',         svg: '/assets/flow/v7/obtain_enc_input.svg' },
   '07': { label: 'Derive Block 0 Key',   svg: '/assets/flow/v7/derive_enc_kM0.svg' },
   '08': { label: 'Encrypt Hint',         svg: '/assets/flow/v7/encrypt_h.svg' },
   '09': { label: 'Derive Commit Key',    svg: '/assets/flow/v7/derive_enc_kC.svg' },
   '0a': { label: 'Derive Hint Nonce',    svg: '/assets/flow/v7/derive_enc_nIVH.svg' },
   '0b': { label: 'Derive Hint Key',      svg: '/assets/flow/v7/derive_enc_kH.svg' },
   '0c': { label: 'Pack Block N AD',      svg: '/assets/flow/v7/pack_adN.svg' },
   '0d': { label: 'Encrypt Block N',      svg: '/assets/flow/v7/encrypt_mN.svg' },
   '0e': { label: 'Derive Block N Key',   svg: '/assets/flow/v7/derive_enc_kMN.svg' },
   '0f': { label: 'Obtain Input',         svg: '/assets/flow/v7/obtain_dec_input.svg' },
   '10': { label: 'Verify Block 0',       svg: '/assets/flow/v7/verify_cd0.svg' },
   '11': { label: 'Verify Block N',       svg: '/assets/flow/v7/verify_cdN.svg' },
   '12': { label: 'Unpack Block 0 AD',    svg: '/assets/flow/v7/unpack_ad0.svg' },
   '13': { label: 'Derive Signing Key',   svg: '/assets/flow/v7/derive_dec_kS.svg' },
   '14': { label: 'Derive Hint Nonce',    svg: '/assets/flow/v7/derive_dec_nIVH.svg' },
   '15': { label: 'Derive Hint Key',      svg: '/assets/flow/v7/derive_dec_kH.svg' },
   '16': { label: 'Derive Block 0 Key',   svg: '/assets/flow/v7/derive_dec_kM0.svg' },
   '17': { label: 'Decrypt Hint',         svg: '/assets/flow/v7/decrypt_hE.svg' },
   '18': { label: 'Derive Commit Key',    svg: '/assets/flow/v7/derive_dec_kC.svg' },
   '19': { label: 'Decrypt Block 0',      svg: '/assets/flow/v7/decrypt_mE0.svg' },
   '1a': { label: 'Decrypt Block N',      svg: '/assets/flow/v7/decrypt_mEN.svg' },
   '1b': { label: 'Unpack Block N AD',    svg: '/assets/flow/v7/unpack_adN.svg' },
   '1c': { label: 'Derive Block N Key',   svg: '/assets/flow/v7/derive_dec_kMN.svg' },
};

// === GENERATED by `pnpm svgo:flow` — do not edit by hand ===
// SHA-256 (base64url) of each flow SVG asset. SvgInlineDirective rejects any
// fetched asset whose bytes do not match
export const FLOW_SVG_HASHES: Record<string, string> = {
   '/assets/flow/v7/encryption.svg': 'sha256-F-TYEyAyyu6lpvwXwoNYufOKEG_X-VK1Lu1J1BvSyiE',
   '/assets/flow/v7/decryption.svg': 'sha256-0eQxQXWJd4LcyaHvE3VT2En6PJvr_3hjuMNQYAFS58Y',
   '/assets/flow/v7/verify_cd0.svg': 'sha256-3fTuekYJvDlqDO6PieB-jWUFuYmlbxv3M8FCbHFitpE',
   '/assets/flow/v7/verify_cdN.svg': 'sha256-PwGeEE9uZHaIaF3hl0YogDxnLuwBbE2LyM3i0qqRHEg',
   '/assets/flow/v7/unpack_ad0.svg': 'sha256-HE_r4q3YVnYXxwq3ruOTSA-XRYGF2KKlDx7xBaCO74U',
   '/assets/flow/v7/derive_dec_kS.svg': 'sha256-TXcn1SWL5qtdO-CDzjTxj-3W9C5lmQP9uWm-MwSr1Ys',
   '/assets/flow/v7/derive_dec_nIVH.svg': 'sha256-AjsqhziAy8ufi0nPVssEAMaJ_GS0GwroGeWCzie_VVM',
   '/assets/flow/v7/derive_dec_kH.svg': 'sha256-DDdKTnTpkHatSQJ5l3DRdBlPbjWvkjzpOQPkL8p4DK8',
   '/assets/flow/v7/derive_dec_kM0.svg': 'sha256-zz5u1lBzzDcc8WjEc6sfAH2oOFk76iifcG-heqKIJyw',
   '/assets/flow/v7/decrypt_hE.svg': 'sha256-Qf_HtW1Zaks6VAONrvKMoBoFeqkLQWDwpC4UKF8Pf_s',
   '/assets/flow/v7/derive_dec_kC.svg': 'sha256-ZaqcpkdtP5XsC4zY46i3RnmCWMULeB8qQrZszxN8m8k',
   '/assets/flow/v7/decrypt_mE0.svg': 'sha256-7vdv8Kjw0vyXYSNZn6oPN7SRIrkWskc-ZJzjOZxHcqU',
   '/assets/flow/v7/sign_cd0.svg': 'sha256-fIUnNgIIB5XHdK5bk2Tbueag1ABPlqeLf8HsH_MN0cM',
   '/assets/flow/v7/sign_cdN.svg': 'sha256-MR2ta_5b907N2yF9iG8IZh_8YVkl8zVSN3sve6d2q08',
   '/assets/flow/v7/encrypt_m0.svg': 'sha256-z683eFGnLG3_3JDp70KTFTJGRwjLvwt-q0808a1aEqc',
   '/assets/flow/v7/pack_ad0.svg': 'sha256-pMfNhpgFBtz6_anF8BvBRMFhai_a3NhSd7DmdGMERSk',
   '/assets/flow/v7/derive_enc_kS.svg': 'sha256-7ANPOVatRreh86WP6hAzPIsQ7rmAOh1R-0TCCq-j3xI',
   '/assets/flow/v7/obtain_enc_input.svg': 'sha256-dNO_-IGKws1bvE1jNp93CfSOFhQD39zWuTgLKUltP8Y',
   '/assets/flow/v7/derive_enc_kM0.svg': 'sha256-rJ6gZuS_ES56j2sOe-ec7r9it324Qod7kyfsuSHG0YE',
   '/assets/flow/v7/encrypt_h.svg': 'sha256-l4A2d2PoheiYeDH5y3j9ZzHNPnEbii71MuJTNcBiYkY',
   '/assets/flow/v7/derive_enc_kC.svg': 'sha256-7fPfMoL5TWxxbjd30HpgpPJXkJX9LmkluafOM7IBv8g',
   '/assets/flow/v7/derive_enc_nIVH.svg': 'sha256-4rFw4SPt81xnWvlE2UKTztlYtJQtw2tQSuSznGHzS9s',
   '/assets/flow/v7/derive_enc_kH.svg': 'sha256-K-bxb37kFEvam0BMY6e3qc73TKzIbqn0DbPj81UGUOk',
   '/assets/flow/v7/pack_adN.svg': 'sha256-0mInm26EQVP1KnKydAsKM4BGAQOcPorp5Lp-3pxyTPw',
   '/assets/flow/v7/encrypt_mN.svg': 'sha256-8x_J_aQLHiPjKsmQkDM2-R9XUx93F9skqQP1ptVKAE0',
   '/assets/flow/v7/derive_enc_kMN.svg': 'sha256-xeqg_U3E09Dxk-eBwimUCFKfOog56BjuJ_m2GP3KY_8',
   '/assets/flow/v7/obtain_dec_input.svg': 'sha256-udar3lHFBVbFKscMYNdHSpPZ4sRMemguLpH6eeRcmtI',
   '/assets/flow/v7/decrypt_mEN.svg': 'sha256-FCnFNNFeYFGt2S-ViHEAdbJkpFuE2TuIcNMqaD212yw',
   '/assets/flow/v7/unpack_adN.svg': 'sha256-7kL0TYFDZ2Lws1f0SYM5rxmaGJguyq2lT7VINQSd104',
   '/assets/flow/v7/derive_dec_kMN.svg': 'sha256-dXqLZ3s4Z0aZ1rUeqz1TKaNySWPDlZnwc-6DjEIdC2w',
};
// === END GENERATED ===
